version: "3.4"
services:
  elasticsearch:
    image: elasticsearch:8.8.1
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /Users/yasin/Docker/elasticsearch/config/:/usr/share/elasticsearch/config/
      - /Users/yasin/Docker/elasticsearch/data/:/usr/share/elasticsearch/data/
    environment:
      - xpack.security.enrollment.enabled=true
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.enabled=false
      - discovery.type=single-node