version: "3.4"
services:
  kibana:
    image: kibana:8.8.1
    container_name: kibana
    environment:
    - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    volumes:
      # - /Users/yasin/Docker/kibana/config/:/usr/share/kibana/config
      - /Users/yasin/Docker/kibana/data/:/usr/share/kibana/data